# Generated by Django 3.2.6 on 2021-08-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20210829_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
    ]
